### ISSUE TITLE
Library `GameUDPProtocol` not found

### ISSUE THREAD

**Issue by haohanyang** [dcronqvist/agame#1]
Can't install it via NuGet.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/37651510/219851601-98b679c2-dc03-40a0-8515-026030375098.png">

**Comment by dcronqvist** [comment]
Hey, that library is unfortunately a local library from a private repository - meaning that you will not be able to get this running on your host.

You can see here that I have a local folder called `_local-dotnet-packages` which I include during restoring, so it looks for packages there too, in addition to NuGet. 

https://github.com/dcronqvist/agame/blob/d0468b522eb2ad90cea92523b86d78a22a88c3b7/agame.csproj#L15

**Comment by haohanyang** [comment]
Is there any way to get this repo?

**Comment by dcronqvist** [comment]
@haohanyang Unfortunately not, I'm not even sure that the repo contains the current code, and it's not something I'm looking to maintain sadly.
